name: "Bug report \U0001F41B"
description: Report errors or unexpected behaviour
title: "bug:"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out a bug report.

        If you are not running the latest version of this module, please try to reproduce your bug with the latest version before opening an issue.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    attributes:
      label: Bootstrap or Starter Module Deployment? (Required)
      description: Do you have a problem with deploying the Bootstrap Resources or the Starter Module through CI/CD?
      multiple: false
      options:
        - bootstrap
        - starter_module
    validations:
      required: true
  - type: input
    id: ps_module
    attributes:
      label: ALZ-PowerShell-Module Version (Required)
      description: Which ALZ-PowerShell-Module version are you using?
      placeholder: Example value, 1.1.6
    validations:
      required: true
  - type: input
    id: alz_tf_acc
    attributes:
      label: alz-terraform-accelerator Version (Required)
      description: Which alz-terraform-accelerator version are you using?
      placeholder: Example value, 1.1.0
    validations:
      required: true
  - type: input
    id: starter_module
    attributes:
      label: Starter Module (Required)
      description: Which Starter Module are you using?
      placeholder: Example value, complete
    validations:
      required: true
  - type: textarea
    id: inputs
    attributes:
      label: Input arguments of the ALZ-PowerShell-Module (Required)
      description: |
        Please provide the input arguments of the ALZ-PowerShell-Module that can reproduce the issue. If not stated explicitly please find these details in the `cache-bootstrap-<VCS>.json` and `cache-starter-<STARTER MODULE NAME>.json` files in the copy of the alz-terraform-accelerator that the ALZ-PowerShell-Module downloaded on execution.
      render: YAML
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Contents of the configuration file used for the `complete` starter module. (Optional)
      description: |
        Please provide contents of the configuration file used for the `complete` starter module.
      render: YAML
  - type: textarea
    id: debug
    attributes:
      label: Debug Output/Panic Output (Optional)
      description: |
        For long debug logs please provide a link to a GitHub Gist containing the complete debug output. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

        To obtain the debug output, see the [Terraform documentation on debugging](https://www.terraform.io/docs/internals/debugging.html).
      render: shell
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour (Required)
      description: What should have happened?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behaviour (Required)
      description: What actually happened?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce (Optional)
      description: |
        Please list the steps required to reproduce the issue, e.g.
  - type: input
    id: facts
    attributes:
      label: Important Factoids (Optional)
      description: |
        Are there anything atypical about your accounts that we should know? For example: Running in a Azure China/Germany/Government?
  - type: textarea
    id: references
    attributes:
      label: References (Optional)
      description: |
        Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

        Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Such as vendor documentation?
