---
name: 02 Azure Landing Zone Continuous Delivery
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Terraform Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - 'apply'
          - 'destroy'

jobs:
  plan_and_apply:
    uses: ${organization_name}/${repository_name_templates}/${cd_template_path}@main
    name: 'CD'
    with:
      terraform_action: $${{ github.event.inputs.terraform_action }}
