module "management_resources" {
  source  = "Azure/avm-ptn-alz-management/azurerm"
  version = "0.9.0"
  count   = var.management_resources_enabled ? 1 : 0
  providers = {
    azurerm = azurerm.management
  }

  automation_account_name                                    = null
  location                                                   = module.config.outputs.management_resource_settings.location
  log_analytics_workspace_name                               = coalesce(module.config.outputs.management_resource_settings.log_analytics_workspace_name, "law-management-${module.config.outputs.management_resource_settings.location}")
  resource_group_name                                        = coalesce(module.config.outputs.management_resource_settings.resource_group_name, "rg-management-${module.config.outputs.management_resource_settings.location}")
  data_collection_rules                                      = module.config.outputs.management_resource_settings.data_collection_rules
  enable_telemetry                                           = var.enable_telemetry
  linked_automation_account_creation_enabled                 = false
  log_analytics_solution_plans                               = module.config.outputs.management_resource_settings.log_analytics_solution_plans
  log_analytics_workspace_allow_resource_only_permissions    = module.config.outputs.management_resource_settings.log_analytics_workspace_allow_resource_only_permissions
  log_analytics_workspace_cmk_for_query_forced               = module.config.outputs.management_resource_settings.log_analytics_workspace_cmk_for_query_forced
  log_analytics_workspace_daily_quota_gb                     = module.config.outputs.management_resource_settings.log_analytics_workspace_daily_quota_gb
  log_analytics_workspace_internet_ingestion_enabled         = module.config.outputs.management_resource_settings.log_analytics_workspace_internet_ingestion_enabled
  log_analytics_workspace_internet_query_enabled             = module.config.outputs.management_resource_settings.log_analytics_workspace_internet_query_enabled
  log_analytics_workspace_local_authentication_enabled       = module.config.outputs.management_resource_settings.log_analytics_workspace_local_authentication_enabled
  log_analytics_workspace_reservation_capacity_in_gb_per_day = module.config.outputs.management_resource_settings.log_analytics_workspace_reservation_capacity_in_gb_per_day
  log_analytics_workspace_retention_in_days                  = module.config.outputs.management_resource_settings.log_analytics_workspace_retention_in_days
  log_analytics_workspace_sku                                = module.config.outputs.management_resource_settings.log_analytics_workspace_sku
  resource_group_creation_enabled                            = true
  sentinel_onboarding                                        = module.config.outputs.management_resource_settings.sentinel_onboarding
  tags                                                       = coalesce(module.config.outputs.management_resource_settings.tags, module.config.outputs.tags)
  timeouts                                                   = module.config.outputs.management_resource_settings.timeouts
  user_assigned_managed_identities                           = module.config.outputs.management_resource_settings.user_assigned_managed_identities
}

moved {
  from = module.management_resources[0].module.management_resources
  to   = module.management_resources[0]
}

# Look up the AMA user assigned managed identity created by the management
# resources module so that we can use its principalId in the cross-scope role
# assignments below. The principalId is not exposed directly by the AVM module
# output, so we read it via the azapi data source.
data "azapi_resource" "ama_user_assigned_managed_identity" {
  count = var.management_resources_enabled && try(module.config.outputs.management_resource_settings.user_assigned_managed_identities.ama, null) != null ? 1 : 0

  type                   = "Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31"
  resource_id            = module.management_resources[0].user_assigned_identity_ids["ama"].id
  response_export_values = ["properties.principalId"]
}

# Explicit Monitoring Contributor role assignment for the AMA user assigned
# managed identity on each Data Collection Rule created by the management
# resources module.
#
# The AMA UAMI is referenced by the AMA related policy assignments
# (`Deploy-VM-ChangeTrack`, `Deploy-VM-Monitoring`, `Deploy-vmArc-ChangeTrack`,
# `Deploy-vmHybr-Monitoring`, `Deploy-VMSS-ChangeTrack`,
# `Deploy-VMSS-Monitoring`) at multiple management group scopes (e.g.
# `Platform` and `Landing Zones`). The `policy_role_assignments` generated by
# the ALZ provider grant the UAMI the required roles within the assignment
# scope, but for assignments outside of the `Platform` MG (where the DCRs
# live) the UAMI lacks `Microsoft.Insights/dataCollectionRules/read` on the
# linked DCRs in the Management subscription. This causes the
# `DeployIfNotExists` evaluation to fail with `LinkedAuthorizationFailed`
# when the policy attempts to create the
# `Microsoft.Insights/dataCollectionRuleAssociations` on a target resource.
#
# Granting `Monitoring Contributor` (749f88d5-cbae-40b8-bcfc-e573ddc772fa)
# explicitly on each DCR resolves this for all assignments using the AMA
# UAMI, regardless of the management group scope they are deployed at.
resource "azapi_resource" "ama_user_assigned_managed_identity_dcr_monitoring_contributor" {
  for_each = var.management_resources_enabled && length(data.azapi_resource.ama_user_assigned_managed_identity) > 0 ? module.management_resources[0].data_collection_rule_ids : {}

  type      = "Microsoft.Authorization/roleAssignments@2022-04-01"
  parent_id = each.value.id
  name      = uuidv5("url", "${each.value.id}|${data.azapi_resource.ama_user_assigned_managed_identity[0].output.properties.principalId}|MonitoringContributor")
  body = {
    properties = {
      principalId      = data.azapi_resource.ama_user_assigned_managed_identity[0].output.properties.principalId
      principalType    = "ServicePrincipal"
      roleDefinitionId = "/subscriptions/${var.subscription_ids["management"]}/providers/Microsoft.Authorization/roleDefinitions/749f88d5-cbae-40b8-bcfc-e573ddc772fa"
    }
  }
}

