# Continuous integration pipeline for ALZ, will validate PRs and
# will produce plan artifact on commit to main

name: alz-ci

variables:
- name: ARM_USE_MSI
  value: true
- name: TF_IN_AUTOMATION
  value: 1

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - .azure-pipelines/**
    - '*.md'

stages:
- stage: prod
  displayName: Prod
  variables:
  - template: ../environments/prod/variables.yml
  pool: alztf
  jobs:
  - job: plan
    displayName: Prod plan & validate
    steps:
      - template: templates/tf-common-plan-steps.yml
