# Continuous deployment pipeline for ALZ, will consume artifact produced by alz-ci pipeline

name: alz-cd

trigger: none

resources:
  pipelines:
  - pipeline: artifact
    source: alz-ci
    branch: main
    trigger:
      branches:
        include:
          - main

variables:
  ARM_USE_MSI: true
  artifactName: tfplan
  TF_IN_AUTOMATION: 1

stages:
- stage: prod
  displayName: PoC
  pool: alztf
  variables:
  - template: ../environments/prod/variables.yml
  jobs:
  - deployment: deploy
    displayName: Prod deployment
    environment: prod
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/tf-common-apply-steps.yml
