---
name: End to End Tests

on:
  pull_request:
    branches:
      - main
    types: ['opened', 'reopened', 'synchronize', 'labeled']
  workflow_dispatch:
    inputs:
      apply:
        description: 'Whether to run the apply and destroy steps'
        default: false
        type: boolean
  schedule:
    - cron: '0 9 * * 1'

permissions:
  id-token: write
  contents: read

jobs:
  define-matrix:
    name: Define Matrix
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Generate Matrix
        id: matrix
        run: |
          $matrix = .github/tests/scripts/generate-matrix.ps1 -runNumber "${{ github.run_number }}" -splitCount 10
          $matrixJson = ConvertTo-Json $matrix -Depth 10 -Compress
          Write-Host (ConvertTo-Json $matrix -Depth 10)
          Write-Output "matrix=$matrixJson" >> $env:GITHUB_OUTPUT
        shell: pwsh

  e2e-test:
    needs: define-matrix
    name: "${{ matrix.name }} (${{ matrix.ShortName }})"
    environment: ${{ github.event_name == 'schedule' && 'CSUTFAUTO' || 'CSUTF' }}
    if: "${{ github.repository == 'Azure/alz-terraform-accelerator' && (contains(github.event.pull_request.labels.*.name, 'PR: Safe to test 🧪') || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') }}"
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.define-matrix.outputs.matrix) }}

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: 1.9.7
          terraform_wrapper: false

      - name: Setup Module Inputs
        run: |

          $subsciptionModulePath = ".github/tests/subscription_lookup"
          terraform -chdir="$subsciptionModulePath" init
          terraform -chdir="$subsciptionModulePath" apply -auto-approve -input=false -var="subscription_display_name=${{ matrix.subscriptionName }}"
          $subscriptionId = (terraform -chdir="$subsciptionModulePath" output -raw subscription_id)

          Write-Host "Subscription ID: $subscriptionId"

          $tfvarsFile = @"
          starter_locations            = ["uksouth", "ukwest"]
          subscription_id_connectivity = "$subscriptionId"
          subscription_id_identity     = "$subscriptionId"
          subscription_id_management   = "$subscriptionId"
          root_parent_management_group_id = "${{ matrix.managementGroupId }}"
          "@

          $tfvarsFile | Out-File -FilePath "${{ matrix.rootModuleFolderPath }}/terraform.tfvars" -Encoding utf8 -Force
        shell: pwsh
        env:
          ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
          ARM_USE_OIDC: true

      - name: Run Terraform
        run: |
          $mode = "${{ matrix.mode }}"
          $sourceVarFilePath = "${{ matrix.configFilePath }}"
          $rootModuleFolderPath = "${{ matrix.rootModuleFolderPath }}"
          $splitNumber = ${{ matrix.splitNumber }}
          $splitIncrement = ${{ matrix.splitIncrement }}

          $success = .github/tests/scripts/terraform-run.ps1 `
            -mode $mode `
            -rootModuleFolderPath $rootModuleFolderPath `
            -sourceVarFilePath $sourceVarFilePath `
            -splitNumber $splitNumber `
            -splitIncrement $splitIncrement

          if(-not $success) {
            Write-Host "Terraform run failed."
            exit 1
          }

        shell: pwsh
        env:
          ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
          ARM_USE_OIDC: true

