---
name: fmt test

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  merge_group:
  workflow_dispatch:

concurrency:
  group: docsfmttest-${{ github.event.pull_request.head.repo.full_name }}/${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docsfmttest:
    name: fmt test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: latest
          terraform_wrapper: false

      - name: Check fmt
        run: |
          echo "==> Running make fmt"
          make fmt
          echo "==> Testing for changes to tracked files"
          CHANGES=$(git status -suno)
          if [ "$CHANGES" ]; then
            echo "Repository formatting or documentation is not correct."
            echo "Run 'make fmt' locally and commit the changes to fix."
            exit 1
          fi
