---
name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Generate Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Zip and Tar
        run: |
          cd templates
          tar -cvzf ../starter_modules.tar.gz .
          zip -r ../starter_modules.zip .

      - name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: starter_modules
          path: |
            starter_modules.tar.gz
            starter_modules.zip

      - name: Check for Valid Git Ref
        if: github.event_name != 'pull_request'
        run: |
          $gitRef = "${{ github.ref }}"
          if (!$gitRef.StartsWith("refs/tags/")) {
            Write-Error "Invalid Git ref $gitRef"
            exit 1
          } else {
            Write-Output "Valid Git ref $gitRef"
          }
        shell: pwsh

      - name: Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./starter_modules.tar.gz
            ./starter_modules.zip
